version: '3.9'

#запускаемые сервисы: django, pgdb, celery и redis
services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    restart: always

  pgdb:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=diploma

  celery:
    build: .
    restart: always
    command: celery -A diploma worker -l info
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
   postgres_data: